import { Target, Eye, Lightbulb, Cpu, Users, GraduationCap } from 'lucide-react'
import { Photo, photos, PageHeader, Reveal, Btn, CountUp, Card, IconBox } from '../components/ui.jsx'
import { stats } from '../data.js'
const vals = [['Expertise', GraduationCap, 'Certified billers and coders train continuously and stay current with payer rules.'], ['Diversity', Users, 'Every practice is different, so we tailor workflows to each client’s needs.'], ['Technology', Cpu, 'We invest in automation and analytics that surface problems before they become denials.'], ['Curiosity', Lightbulb, 'We question the status quo and test better ways to get practices paid.']]
export default function About() {
  return <><PageHeader title="About us" sub="We are here for your care" crumbs={['About']} />
    <section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-20 md:grid-cols-2"><Reveal><Photo src={photos.doc1} className="mx-auto h-[420px] w-full max-w-sm"><span className="absolute bottom-6 right-4 animate-float rounded-xl bg-white px-3 py-2 text-sm font-semibold shadow-xl">Care first, billing second</span></Photo></Reveal>
      <Reveal d={150}><h2 className="text-4xl">About United MD Solutions</h2><p className="mt-4 text-slate-600">United MD Solutions is a medical billing partner offering billing, coding and revenue cycle services to practices across the country.</p>
        {[['Our mission', Target, 'Give providers accurate, efficient billing so they can focus on patient care.'], ['Our vision', Eye, 'Raise the standard of billing through better tools and accountable service.']].map(([t, I, d]) => <div key={t} className="mt-6 flex gap-4"><IconBox icon={I} /><div><h3 className="text-xl">{t}</h3><p className="text-slate-600">{d}</p></div></div>)}</Reveal></section>
    <section className="grid-bg bg-navy py-14 text-white"><div className="mx-auto max-w-6xl px-5"><h2 className="mb-8 text-center text-3xl text-white">What makes us different</h2><div className="grid grid-cols-2 gap-6 text-center md:grid-cols-5">{stats.map(([v, l]) => <div key={l}><div className="font-serif text-4xl text-gold2"><CountUp value={v} /></div><p className="text-sm text-white/80">{l}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-20"><h2 className="mb-10 text-center text-3xl">Our company values</h2><div className="grid gap-6 md:grid-cols-2">{vals.map(([t, I, d], k) => <Reveal key={t} d={k * 100}><Card className="flex gap-4"><IconBox icon={I} tone="navy" /><div><h3 className="text-xl">{t}</h3><p className="mt-1 text-slate-600">{d}</p></div></Card></Reveal>)}</div></section>
    <section className="mx-auto max-w-4xl px-5"><div className="grid-bg rounded-3xl bg-navy2 p-12 text-center text-white"><h2 className="text-3xl text-white">Let’s review your billing together</h2><p className="mx-auto my-4 max-w-xl text-white/80">If your team spends more time on paperwork than patients, it may be time for a closer look.</p><Btn light to="/contact">Let’s connect</Btn></div></section></>
}
