import { useState } from 'react'
import { TrendingUp, Headset, BarChart3, Users, Rocket, Briefcase, Calculator, Cpu, Scale, Megaphone, Handshake, UserCheck, FileText, Send, Eye, DollarSign, ChevronDown, CheckCircle2 } from 'lucide-react'
import { Photo, photos, PageHeader, Reveal, Btn, Title, Card, IconBox } from '../components/ui.jsx'
import { faqs } from '../data.js'
const why = [['Revenue performance', TrendingUp], ['Patient access', Headset], ['Operational efficiency', BarChart3], ['Staffing flexibility', Users], ['Growth readiness', Rocket]]
const who = [['Healthcare consultants', Briefcase], ['CFO advisors', BarChart3], ['Billing consultants', Calculator], ['Transformation experts', Rocket], ['EHR & tech consultants', Cpu], ['CPA firms', FileText], ['Healthcare attorneys', Scale], ['Industry influencers', Megaphone], ['Existing clients', Handshake]]
const tiers = [['Small practice', 'Under $50k collections', '$400', '3%'], ['Growth practice', '$50k – $150k', '$900', '5%'], ['Enterprise practice', '$150k+', '$1,800', '7%']]
const ben = ['Lifetime recurring commissions', 'Transparent referral tracking', 'Dedicated partner success team', 'Monthly ACH / wire payouts', 'Marketing and sales support', 'Non-exclusive flexibility']
const how = [['Apply', UserCheck, 'Complete the short partner form.'], ['Get approved', CheckCircle2, 'We review your profile and activate your account.'], ['Refer', Send, 'Submit prospects through your dashboard.'], ['Track', Eye, 'Follow each opportunity in real time.'], ['Earn', DollarSign, 'Receive bonuses and monthly commissions.']]
export default function Partner() {
  const [open, setOpen] = useState(0)
  return <><PageHeader title="Partner program" sub="Help providers grow. Earn while they succeed." crumbs={['Partner']} />
    <section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-16 md:grid-cols-2"><Reveal><p className="font-semibold text-gold">MedRevu Partner Program</p><h2 className="mt-2 text-4xl leading-tight">Refer practices. <span className="text-navy2">Earn recurring income.</span></h2>
      <p className="mt-4 text-lg text-slate-600">Introduce healthcare providers to certified billing experts. We handle onboarding, billing and collections while you earn a bonus and a monthly commission for every active client.</p>
      <div className="mt-7 flex flex-wrap gap-4"><Btn to="/contact">Apply now</Btn><Btn light to="/contact" icon={Handshake}>Talk to our team</Btn></div></Reveal>
      <Reveal d={150}><Photo src={photos.nurse} blob={false} className="mx-auto aspect-[1295/1208] w-full max-w-lg" alt="Healthcare professional holding a clipboard" /></Reveal></section>
    <section className="mx-auto max-w-5xl px-5 py-16"><Title>Why partner with us?</Title><div className="grid grid-cols-2 gap-6 text-center md:grid-cols-5">{why.map(([t, I], k) => <Reveal key={t} d={k * 80}><div className="group"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-navy text-gold2 transition group-hover:-translate-y-2 group-hover:rotate-6"><I /></span><p className="mt-3 text-sm font-semibold">{t}</p></div></Reveal>)}</div>
      <Reveal><p className="mx-auto mt-10 max-w-lg rounded-2xl bg-gradient-to-r from-navy to-navy2 p-6 text-center font-serif text-xl text-white">You bring the relationship. We deliver the operational excellence.</p></Reveal></section>
    <section className="bg-mist py-16"><div className="mx-auto max-w-5xl px-5"><Title>Who can join?</Title><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{who.map(([t, I], k) => <Reveal key={t} d={(k % 3) * 80}><Card className="flex items-center gap-3 !p-4"><IconBox icon={I} size={20} tone="navy" />{t}</Card></Reveal>)}</div></div></section>
    <section className="mx-auto max-w-5xl px-5 py-16"><Title sub="Commissions are earned on paid client invoices and continue while the client stays active.">Earn more as your referrals grow</Title><div className="grid gap-6 md:grid-cols-3">{tiers.map(([n, r, b, c], k) => <Reveal key={n} d={k * 100}><Card className={`text-center ${k === 1 ? 'border-gold ring-2 ring-gold' : ''}`}><p className="text-sm text-slate-500">Tier {k + 1}</p><h3 className="text-xl">{n}</h3><p className="text-xs text-slate-500">{r}</p><p className="mt-5 font-serif text-4xl text-navy2">{b}</p><p className="text-xs">One-time bonus</p><p className="mt-4 font-serif text-4xl text-navy2">{c}</p><p className="text-xs">Monthly commission</p></Card></Reveal>)}</div></section>
    <section className="grid-bg bg-navy py-16"><div className="mx-auto max-w-5xl px-5"><h2 className="mb-8 text-center text-3xl text-white">Partner benefits</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{ben.map((t, k) => <Reveal key={t} d={(k % 3) * 80}><div className="flex items-center gap-3 rounded-xl bg-white p-4 font-semibold text-navy transition hover:-translate-y-1"><CheckCircle2 className="text-gold" />{t}</div></Reveal>)}</div></div></section>
    <section className="mx-auto max-w-5xl px-5 py-16"><Title>How it works</Title><div className="relative grid gap-8 text-center md:grid-cols-5"><div className="absolute left-[10%] right-[10%] top-8 hidden h-0.5 bg-gold/50 md:block" />{how.map(([t, I, d], k) => <Reveal key={t} d={k * 120}><div className="relative"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-navy text-gold2 ring-4 ring-white"><I /></span><h3 className="mt-3 text-lg">{t}</h3><p className="text-sm text-slate-600">{d}</p></div></Reveal>)}</div></section>
    <section className="mx-auto max-w-4xl px-5"><div className="relative flex flex-wrap items-center justify-between gap-5 overflow-hidden rounded-3xl bg-gradient-to-r from-navy to-navy2 p-10 text-white md:pr-80"><Photo src={photos.manager} blob={false} className="pointer-events-none absolute bottom-0 right-2 hidden h-64 w-72 md:block" alt="Partner success manager" /><div><h2 className="text-3xl text-white">Start monetizing your network</h2><p className="mt-2 text-white/80">Help providers improve collections while you build recurring income.</p></div><Btn light to="/contact">Become a partner</Btn></div></section>
    <section className="mx-auto max-w-3xl px-5 py-16"><Title>Frequently asked questions</Title><div className="space-y-3">{faqs.map(([q, a], k) => <div key={q} className="overflow-hidden rounded-xl bg-white shadow-md"><button onClick={() => setOpen(open === k ? -1 : k)} className="flex w-full items-center justify-between p-5 text-left font-semibold">{q}<ChevronDown className={`transition-transform duration-300 ${open === k ? 'rotate-180 text-gold' : ''}`} /></button><div className={`grid transition-all duration-300 ${open === k ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}><p className="overflow-hidden px-5 text-slate-600"><span className="block pb-5">{a}</span></p></div></div>)}</div></section></>
}
